name: CI - Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.18.3
        uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
          node-version: 14.18.3
          cache: 'npm'
      - name: Installing dependencies
        run: npm install
      - name: Building the Application
        run: npm run build
      - name: Publish the Application
        run: npm publish
