name: CI - Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.18.3
        uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/
          node-version: 14.18.3
          cache: 'npm'
      - name: Intstalling dependencies
        run: npm install
      - name: Building the Application
        run: npm run build

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.18.3
        uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/
          node-version: 14.18.3
          cache: 'npm'
      - name: Intstalling dependencies
        run: npm install
      - name: Building the Application
        run: npm test
